pipeline:
  identifier: Build_Sainarasimhan_kafka_1739125525884
  name: Build kafka
  orgIdentifier: default
  projectIdentifier: Testharness
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Sainarasimhan/kafka
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: RunTests
                  name: Run Tests with Intelligence
                  identifier: Run_Tests_with_Intelligence
                  spec:
                    language: Java
                    buildTool: Gradle
                    args: "--build-cache unitTest -PmaxParallelForks=32 -PignoreFailures=true"
                    packages: org.apache.kafka,kafka.test,kafka.testkit,kafka.server,kafka.tools,kafka.examples,test.plugins
                    runOnlySelectedTests: true
                    preCommand: ls
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
